// Ελληνικό λεξικό ετικετών — όλα τα user-facing strings από εδώ
export const L = {
  appName: "Mission Control",
  agents: "Πράκτορες",
  runs: "Εκτελέσεις",
  liveFeed: "Ζωντανή ροή",
  newRun: "Νέα εκτέλεση",
  task: "Εργασία",
  agent: "Πράκτορας",
  statusLabel: "Κατάσταση",
  duration: "Διάρκεια",
  createdAt: "Δημιουργήθηκε",
  available: "Διαθέσιμο",
  notInstalled: "Μη εγκατεστημένο",
  submit: "Εκτέλεση",
  noRuns: "Δεν υπάρχουν εκτελέσεις ακόμα.",
  noEvents: "Αναμονή γεγονότων…",
  apiDown: "Ο server του Mission Control δεν είναι διαθέσιμος (uv run mission-control serve).",
  log: "Log",
  backToRuns: "← Όλες οι εκτελέσεις",
  exitCode: "Κωδικός εξόδου",
  estCost: "εκτ. κόστος/run",
} as const;

export const L2 = {
  inbox: "Inbox",
  memory: "Μνήμη",
  ask: "Ρώτησε",
  budgets: "Budgets",
  connectors: "Connectors",
  standards: "Κανόνες",
  journal: "Ημερολόγιο",
  addToInbox: "Προσθήκη στο inbox…",
  add: "Προσθήκη",
  triageAll: "Ταξινόμηση νέων",
  triageAI: "με AI",
  inboxEmpty: "Το inbox είναι άδειο — inbox zero ✨",
  vault: "Vault",
  notes: "Σημειώσεις",
  topTags: "Κορυφαία tags",
  searchMemory: "Αναζήτηση στη μνήμη…",
  search: "Αναζήτηση",
  noResults: "Δεν βρέθηκε τίποτα.",
  regenMoc: "Ανανέωση MOC",
  askPlaceholder: "Ρώτησε ό,τι θες — ψάχνει σε notes, runs, inbox…",
  askButton: "Ρώτα",
  synthesize: "Σύνθεση απάντησης με AI (κοστίζει 1 run)",
  sources: "Πηγές",
  answer: "Απάντηση",
  noAnswer: "Χωρίς AI σύνθεση — δες τις πηγές.",
  monthSpend: "Μήνας (€)",
  todayRuns: "Runs σήμερα",
  fixedRules: "Πάγιοι κανόνες (profile.yaml)",
  learnedRules: "Κανόνες που έμαθε το OS",
  detectPatterns: "Ανίχνευση patterns",
  noRules: "Δεν υπάρχουν κανόνες ακόμα.",
  newAgent: "Νέος πράκτορας",
  create: "Δημιουργία",
  dailyRecap: "Ημερήσιο recap",
  weeklyReview: "Εβδομαδιαίο review",
  generate: "Δημιουργία",
  working: "Επεξεργασία…",
  installHint: "Το CLI δεν βρέθηκε στο PATH — εγκατάστησέ το και θα γίνει ✓ αυτόματα.",
  room: "Σύσκεψη",
  roomHint: "Ίδιο task σε πολλούς πράκτορες — σύγκρινε τις απαντήσεις δίπλα-δίπλα.",
  selectAgents: "Διάλεξε πράκτορες (τουλάχιστον 2)",
  startRoom: "Ξεκίνα σύσκεψη",
  skippedAgents: "Παραλείφθηκαν λόγω budget",
  artifacts: "Δημιουργίες",
  artifactsEmpty: "Δεν υπάρχουν δημιουργίες ακόμα — τρέξε κάτι!",
  allKinds: "Όλα",
  model: "Μοντέλο",
} as const;

export const ARTIFACT_KIND_LABELS: Record<string, string> = {
  log: "📜 Log",
  note: "🧠 Σημείωση",
  file: "📄 Αρχείο",
  output: "📦 Output",
};

export const KIND_LABELS: Record<string, string> = {
  task: "Εργασία",
  project: "Project",
  reference: "Αναφορά",
  archive: "Αρχείο",
  review: "Για έλεγχο",
};

export const STATUS_LABELS: Record<string, string> = {
  queued: "Σε αναμονή",
  running: "Σε εξέλιξη",
  done: "Ολοκληρώθηκε",
  error: "Σφάλμα",
  cancelled: "Ακυρώθηκε",
};

export const SCOPE_LABELS: Record<string, string> = {
  arivia: "Arivia",
  titan: "Titan",
  personal: "Personal",
};
